### ISSUE TITLE
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by RasmusBacklund** [Jeffrey-van-Ham/ticketswap-crawler#1]
There is no uri under listing on line 45 `        const url = HOST + listing.uri.path;
`

**Comment by Jeffrey-van-Ham** [comment]
The example url is from an expired event. When I try an active event it does work. For example try and change EVENT_URL to `/event/dgtl-presents-ben-bohmer-live-ade/regular-tickets/53697c81-a8de-44f4-abb6-d34778e4e1cf/2283730`

**Comment by RasmusBacklund** [comment]
Yep, my bad, sorry about that... BTW, do you know about how long you can use it and for how long you will be disabled before being able to use it again?

**Comment by Jeffrey-van-Ham** [comment]
Not sure. Hit or miss. I think it will work for 30 min to an hour and if I would guess they will block your ip for about 2 hours or something.
